name: 编译

on:
  workflow_dispatch:

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: 仓库检出
        uses: actions/checkout@v4.2.2
      - name: 设置 python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'
      - name: 安装依赖&编译
        run: |
          pip install -r requirements.txt -U pyinstaller
          pyinstaller -F -w -i icon\icon.jpeg main.py
      - name: 移动文件
        run: |
          move outputs dist/outputs
          move ttf_library dist/ttf_library
      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: HandWrite-Windows
          path: dist
  Linux:
    runs-on: ubuntu-latest
    steps:
      - name: 仓库检出
        uses: actions/checkout@v4.2.2
      - name: 设置 python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.9'
      - name: 安装依赖&编译
        run: |
          pip install -r requirements.txt -U pyinstaller
          pyinstaller -F main.py
      - name: 移动文件
        run: |
          move outputs dist/outputs
          move ttf_library dist/ttf_library
      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: HandWrite-Linux
          path: dist
